{
 "title": "Websites - All",
 "tags": [ "Website" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "filename",
    "label": "Filename",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(filename) (count_over_time({filename=\"$filename\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Visitor per Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({filename=\"$filename\"} | json | unwrap bytes_sent [$__interval]))"
    }
   ]
  },
  {
   "title": "Request per status code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "HTTP status: {{status}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "status: {{status}}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(request_method) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "Method: {{request_method}}"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_user_agent) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "Browser: {{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Basic Auth Users",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(remote_user) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "Remote user: {{remote_user}}"
    }
   ]
  },
  {
   "title": "Status in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "status: {{status}}"
    }
   ]
  },
  {
   "title": "Methods in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum by(request_method) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "Method: {{request_method}}"
    }
   ]
  },
  {
   "title": "Browsers in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "sum by(http_user_agent) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "Browser: {{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Basic Auth Users in time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "expr": "sum by(remote_user) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "User: {{remote_user}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top Websites",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum by(server_name) (count_over_time({filename=\"$filename\"}| json [$__interval]))",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  { "title": "Bad requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Top (bad) IPs",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"401\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"403\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"404\" | server_name = \"grafana.psdm.ch\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"400\" | server_name = \"grafana.psdm.ch\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"500\" | server_name = \"grafana.psdm.ch\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"502\" | server_name = \"grafana.psdm.ch\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"301\" | server_name = \"grafana.psdm.ch\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top bad Basic Auth Users",
   "type": "table",
   "description": "List of all users that received a \"401\" (unauthorized) status",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 32 },
   "targets": [
    {
     "expr": "sum by(remote_user) (count_over_time({filename=\"$filename\"}| json | status=\"401\" [$__interval]))",
     "legendFormat": "{{remote_user}}"
    }
   ]
  },
  {
   "title": "Top (bad) request_uri",
   "type": "table",
   "description": "All request_uri that get a status between the following: 401,403,404,400,500,502,301",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 32 },
   "targets": [
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"401\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"403\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"404\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"400\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"500\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"502\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"301\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{filename=\"$filename\"} | json | line_format \"Request for {{.request_uri}} with HTTP status {{.status}}\""
    }
   ]
  },
  {
   "title": "Archives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum by(status) (count_over_time({filename=\"/var/log/after.log\"}[$__interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "type": "geomap",
     "gridPos": { "h": 7, "w": 5, "x": 1, "y": 70 },
     "targets": [
      {
       "expr": "sum by (geoip2_data_country_code) (count_over_time({filename=\"/var/log/after.log\"}[$__interval]))",
       "legendFormat": "{{geoip2_data_country_code}}"
      }
     ]
    },
    {
     "title": "Country",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "panelId": 8 }
     ]
    },
    {
     "title": "City",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(geoip2_data_city_name) (count_over_time({filename=\"/var/log/analytics.log\"}| json [$__interval]))",
       "legendFormat": "{{geoip2_data_city_name}}"
      }
     ]
    },
    {
     "title": "Top HTTP Referers",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(http_referer) (count_over_time({filename=\"/var/log/analytics.log\"}| json [$__interval]))",
       "legendFormat": "{{http_referer}}"
      }
     ]
    },
    {
     "title": "Top Requested Pages",
     "type": "table",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(request_uri) (count_over_time({filename=\"/var/log/all_proxy_access.log\"}| status != 200 [$__interval]))",
       "legendFormat": "{{request_uri}}"
      }
     ]
    },
    {
     "title": "Top IPs",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(remote_addr) (count_over_time({filename=\"/var/log/analytics.log\"}| json [$__interval])) ",
       "legendFormat": "{{remote_addr}}"
      }
     ]
    },
    {
     "title": "Top User Agents",
     "type": "table",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(http_user_agent) (count_over_time({filename=\"/var/log/after.log\"} [$__interval]))",
       "legendFormat": "{{http_user_agent}}"
      }
     ]
    },
    {
     "title": "Raw data",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/after.log\"} | json "
      }
     ]
    },
    {
     "title": "Raw data",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "{filename=\"/var/log/after.log\"} | json "
      }
     ]
    }
   ]
  }
 ]
}