{
 "title": "Websites",
 "tags": [ "Website" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "filename",
    "label": "Filename",
    "query": {}
   },
   {
    "name": "website",
    "label": "Website",
    "query": "your-domain1.com,your-domain2.com,your-domain3.com,your-domain4.com"
   }
  ]
 },
 "panels": [
  { "title": "$website", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(filename) (count_over_time({filename=\"$filename\"}| json | server_name = \"$website\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Visitor per Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"$filename\"}| json | server_name = \"$website\"[$__interval])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({filename=\"$filename\"} | json | unwrap bytes_sent | server_name = \"$website\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Request per status code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({filename=\"$filename\"}| json | server_name = \"$website\" [$__interval]))",
     "legendFormat": "HTTP status: {{status}}"
    }
   ]
  },
  {
   "title": "Pie chart - Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({filename=\"$filename\"}| json | server_name = \"$website\" [$__interval]))",
     "legendFormat": "status: {{status}}"
    }
   ]
  },
  {
   "title": "Pie chart - Method",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(request_method) (count_over_time({filename=\"$filename\"}| json | server_name = \"$website\" [$__interval]))",
     "legendFormat": "Method: {{request_method}}"
    }
   ]
  },
  {
   "title": "Top IPs of \"$website\"",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"}| json | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  { "title": "Bad Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Top (bad) IPs - \"$website\"",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"401\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"403\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"404\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"400\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"500\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"502\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "expr": "sum by(remote_addr) (count_over_time({filename=\"$filename\"} | json | status = \"301\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top (bad) request_uri - \"$website\"",
   "type": "table",
   "description": "All request_uri that get a status between the following: 401,403,404,400,500,502,301",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"401\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"403\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"404\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"400\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"500\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"502\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    },
    {
     "expr": "sum by(request_uri) (count_over_time({filename=\"$filename\"} | json | status = \"301\" | server_name = \"$website\" [$__interval]))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{filename=\"$filename\"} | json | server_name = `$website` | line_format `Request for {{.request_uri}} with HTTP status {{.status}}`"
    }
   ]
  }
 ]
}